spring:
  application:
    name: beluga
  main:
    web-application-type: servlet
  flyway:
    enabled: true
    baseline-version: 0

# Defaults
beluga:
  persistence:
    type: SQLITE
  result-storage:
    type: FILE_SYSTEM