openapi: 3.0.0
info:
  title: Job's REST API
  version: '1.0'
paths:
  /jobs:
    post:
      description: Creates a new job
      tags:
        - Job
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/createJob"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/job"
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/badRequestResponse"
  /jobs/{jobId}:
    get:
      description: Retrieve a job
      tags:
        - Job
      parameters:
        - in: path
          name: jobId
          required: true
          schema:
            type: integer
            example: 123
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/job"
        404:
          description: NOT FOUND
    put:
      description: Update a job
      tags:
        - Job
      parameters:
        - in: path
          name: jobId
          required: true
          schema:
            type: integer
            example: 123
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/createJob"
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/job"
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/badRequestResponse"
        404:
          description: NOT FOUND

components:
  schemas:

    createJob:
      type: object
      properties:
        name:
          type: string
          example: job-name
        execution:
          $ref: "#/components/schemas/createExecutionConfiguration"
        scraping:
          $ref: "#/components/schemas/createScrapingConfiguration"
      required:
        - name
        - execution
        - scraping

    updateJob:
      type: object
      allOf:
        - $ref: "#/components/schemas/createJob"

    job:
      type: object
      properties:
        id:
          type: integer
          example: 123
        name:
          type: string
          example: job-name
        execution:
          $ref: "#/components/schemas/executionConfiguration"
        scraping:
          $ref: "#/components/schemas/scrapingConfiguration"
      required:
        - id
        - name
        - execution
        - scraping

    createExecutionConfiguration:
      type: object
      properties:
        workers:
          type: integer
          example: 1
        tasksPerSecond:
          type: integer
          example: 5
      required:
        - workers
        - tasksPerSecond

    executionConfiguration:
      type: object
      allOf:
        - $ref: "#/components/schemas/createExecutionConfiguration"
      properties:
        id:
          type: integer
          example: 123
      required:
        - id

    createScrapingConfiguration:
      type: object
      properties:
        itemSelector:
          type: string
          example: main#content
          description: Css selector
        dataPoints:
          type: array
          items:
            $ref: "#/components/schemas/writeScrapingDataPointDto"
          minLength: 1
      required:
        - itemSelector
        - dataPoints

    scrapingConfiguration:
      type: object
      properties:
        id:
          type: integer
          example: 123
        itemSelector:
          type: string
          example: main#content
          description: Css selector
        dataPoints:
          type: array
          items:
            $ref: "#/components/schemas/readScrapingDataPointDto"
          minLength: 1
      required:
        - id
        - itemSelector
        - dataPoints

    writeScrapingDataPointDto:
      type: object
      properties:
        selector:
          type: string
          example: main#content
          description: Css selector
        extraction:
          oneOf:
            - $ref: "#/components/schemas/writeAttributeExtractionConfigurationDto"
            - $ref: "#/components/schemas/writeDescriptionListExtractionConfigurationDto"
            - $ref: "#/components/schemas/writeHtmlExtractionConfigurationDto"
            - $ref: "#/components/schemas/writeImageExtractionConfigurationDto"
            - $ref: "#/components/schemas/writeTextExtractionConfigurationDto"
      required:
        - selector
        - extraction

    readScrapingDataPointDto:
      type: object
      properties:
        id:
          type: integer
          example: 123
        selector:
          type: string
        extraction:
          oneOf:
            - $ref: "#/components/schemas/readAttributeExtractionConfigurationDto"
            - $ref: "#/components/schemas/readDescriptionListExtractionConfigurationDto"
            - $ref: "#/components/schemas/readHtmlExtractionConfigurationDto"
            - $ref: "#/components/schemas/readImageExtractionConfigurationDto"
            - $ref: "#/components/schemas/readTextExtractionConfigurationDto"
      required:
        - id
        - selector

    dataPointType:
      type: string
      enum:
        - IMAGE
        - TEXT
        - HTML

    writeAttributeExtractionConfigurationDto:
      type: object
      properties:
        type:
          type: string
          enum:
            - ATTRIBUTE
        field:
          type: string
          example: output.field
        attribute:
          type: string
      required:
        - type
        - field
        - attribute

    readAttributeExtractionConfigurationDto:
      type: object
      allOf:
        - $ref: "#/components/schemas/writeAttributeExtractionConfigurationDto"
      properties:
        id:
          type: integer
          example: 123
      required:
        - id

    writeDescriptionListExtractionDataPointConfigurationDto:
      type: object
      properties:
        dtValue:
          type: string
        field:
          type: string
      required:
        - dtValue
        - field

    readDescriptionListExtractionDataPointConfigurationDto:
      type: object
      allOf:
        - $ref: "#/components/schemas/writeDescriptionListExtractionDataPointConfigurationDto"
      properties:
        id:
          type: integer
          example: 123
      required:
        - id

    writeDescriptionListExtractionConfigurationDto:
      type: object
      properties:
        type:
          type: string
          enum:
            - DESCRIPTION_LIST
        dataPoints:
          type: array
          items:
            $ref: "#/components/schemas/writeDescriptionListExtractionDataPointConfigurationDto"
      required:
        - type
        - dataPoints

    readDescriptionListExtractionConfigurationDto:
      type: object
      properties:
        id:
          type: integer
          example: 123
        type:
          type: string
          enum:
            - DESCRIPTION_LIST
        dataPoints:
          type: array
          items:
            $ref: "#/components/schemas/readDescriptionListExtractionDataPointConfigurationDto"
      required:
        - id
        - type
        - dataPoints

    writeHtmlExtractionConfigurationDto:
      type: object
      properties:
        type:
          type: string
          enum:
            - HTML
        field:
          type: string
      required:
        - type
        - field

    readHtmlExtractionConfigurationDto:
      type: object
      allOf:
        - $ref: "#/components/schemas/writeHtmlExtractionConfigurationDto"
      properties:
        id:
          type: integer
          example: 123
      required:
        - id

    writeImageExtractionConfigurationDto:
      type: object
      properties:
        type:
          type: string
          enum:
            - IMAGE
      required:
        - type

    readImageExtractionConfigurationDto:
      type: object
      allOf:
        - $ref: "#/components/schemas/writeImageExtractionConfigurationDto"
      properties:
        id:
          type: integer
          example: 123
      required:
        - id

    writeTextExtractionConfigurationDto:
      type: object
      properties:
        type:
          type: string
          enum:
            - TEXT
        field:
          type: string
      required:
        - type
        - field

    readTextExtractionConfigurationDto:
      type: object
      allOf:
        - $ref: "#/components/schemas/writeTextExtractionConfigurationDto"
      properties:
        id:
          type: integer
          example: 123
      required:
        - id

    badRequestResponse:
      type: object
      properties:
        message:
          type: string
          example: some property was null but expected not null
      required:
        - message