spring:
  application:
    name: x-scraper
  main:
    web-application-type: servlet
#  profiles:
#    active:
#      - local
  flyway:
    enabled: true
    locations: classpath:db
    baseline-version: 0
    default-schema: x_scraper