package com.beluga.mapper.job.scraping_configuration.extraction_definition.description_list;

import com.beluga.api.job.dto.read.extraction_configuration.description_list.ReadDescriptionListExtractionDataPointConfigurationDto;
import com.beluga.api.job.dto.write.extraction_configuration.description_list.WriteDescriptionListExtractionDataPointConfigurationDto;
import com.beluga.model.job_definition.configuration.scraping_configuration.extraction_definition.description_list.DescriptionListExtractionDataPointDefinition;
import com.beluga.properties.scraping.extraction_configuration.DescriptionListExtractionConfigurationDataPointProperties;
import org.mapstruct.Mapper;

import static org.mapstruct.MappingConstants.ComponentModel.SPRING;

@Mapper(componentModel = SPRING)
public interface DescriptionListDataPointDefinitionMapper {

    DescriptionListExtractionDataPointDefinition map(WriteDescriptionListExtractionDataPointConfigurationDto dto);

    DescriptionListExtractionDataPointDefinition map(DescriptionListExtractionConfigurationDataPointProperties properties);

    ReadDescriptionListExtractionDataPointConfigurationDto map(DescriptionListExtractionDataPointDefinition definition);
}
